name: Test & Deploy

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Update website to master on webserver
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: tede
        key: ${{ secrets.SSH_PRIVKEY }}
        commands: | 
          cd /home/tede/tedemehrtens.de
          git pull
          bundle install --path vendor/bundle
          bundle exec jekyll build -d /var/www/virtual/$USER/html
                
